package com.example.flow_board.domain.whiteboard.websocket;

public enum WhiteboardEventType {
  STROKE_CREATED,
  STROKE_DELETED,
  CLEARED,

  OBJECT_CREATED,
  OBJECT_UPDATED,
  OBJECT_DELETED,

  WORKSPACE_UPDATED,

  OBJECT_LIVE_EDIT,
  OBJECT_LIVE_MOVE,
  OBJECT_LIVE_RESIZE,

  STROKE_LIVE_START,
  STROKE_LIVE_APPEND,
  STROKE_LIVE_END,

  CURSOR_MOVED
}
