server:
  port: 8080

spring:
  application:
    name: backend-template

  datasource:
    url: jdbc:mysql://localhost:33080/backend_template
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000